name: schedule job

on:
  schedule:
    - cron: "0 0 * * *"
    
  jobs:
    run-script:
      run-on: unbntu-latest

      steps:
        name: print Massage
         run: echo "Schedule workflow executed"  
  
